cpln:
  gvc: development
  org: cpln-git-deploy
service: pct-monitor
version: 1
workloads:
  - dockerfile: Dockerfile
    healthPath: /
    name: pct-monitor
    port: 8080
    type: web
    workload: pct-monitor
