# fly.toml app configuration file generated for pct-monitor on 2026-02-24T10:05:38-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pct-monitor'
primary_region = 'dfw'

[build]

[env]
  DATA_DIR = '/data'

[[mounts]]
  source = 'pct_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
